'use client'

import { useState, useEffect } from 'react'
import Link from 'next/link'

interface InventoryItem {
  id: number
  sku: string
  name: string
  productType: string
  flavor: string | null
  currentStock: number
  minStock: number
}

interface StockTask {
  id: number
  inventoryItemId: number
  inventoryItemName: string
  productType: string
  flavor: string | null
  taskType: string
  taskName: string
  targetQuantity: number
  completedQuantity: number
  status: string
  scheduledDate: string
  durationMinutes: number | null
  assignedTo: string | null
  priority: number
  isAutoGenerated: boolean
}

interface DateGroup {
  date: string
  tasks: StockTask[]
}

interface Staff {
  id: number
  name: string
}

export default function StockProductionPage() {
  const [tasksByDate, setTasksByDate] = useState<DateGroup[]>([])
  const [inventory, setInventory] = useState<InventoryItem[]>([])
  const [staff, setStaff] = useState<Staff[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [filter, setFilter] = useState<'all' | 'pending' | 'in_progress'>('pending')
  const [showNewTaskModal, setShowNewTaskModal] = useState(false)

  useEffect(() => {
    loadData()
  }, [filter])

  const loadData = async () => {
    setLoading(true)
    try {
      const statusParam = filter !== 'all' ? `&status=${filter.toUpperCase()}` : ''
      const [tasksRes, inventoryRes, staffRes] = await Promise.all([
        fetch(`/api/stock-tasks?groupByDate=true${statusParam}`),
        fetch('/api/inventory?lowStock=true'),
        fetch('/api/staff?isActive=true')
      ])

      if (!tasksRes.ok) throw new Error('Failed to load tasks')

      const tasksData = await tasksRes.json()
      setTasksByDate(tasksData.tasks || [])

      if (inventoryRes.ok) {
        const inventoryData = await inventoryRes.json()
        setInventory(inventoryData)
      }

      if (staffRes.ok) {
        const staffData = await staffRes.json()
        setStaff(staffData)
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load data')
    } finally {
      setLoading(false)
    }
  }

  const handleStartTask = async (taskId: number) => {
    try {
      const res = await fetch(`/api/stock-tasks/${taskId}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ status: 'IN_PROGRESS', startedAt: new Date().toISOString() })
      })
      if (!res.ok) throw new Error('Failed to start task')
      await loadData()
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to start task')
    }
  }

  const handleCompleteTask = async (taskId: number) => {
    try {
      const res = await fetch(`/api/stock-tasks/${taskId}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({})
      })
      if (!res.ok) throw new Error('Failed to complete task')
      await loadData()
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to complete task')
    }
  }

  const formatDate = (dateStr: string) => {
    const date = new Date(dateStr + 'T12:00:00')
    const today = new Date()
    const tomorrow = new Date(today)
    tomorrow.setDate(tomorrow.getDate() + 1)

    if (date.toDateString() === today.toDateString()) return 'Today'
    if (date.toDateString() === tomorrow.toDateString()) return 'Tomorrow'

    return date.toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' })
  }

  const totalTasks = tasksByDate.reduce((sum, g) => sum + g.tasks.length, 0)
  const totalQuantity = tasksByDate.reduce(
    (sum, g) => sum + g.tasks.reduce((s, t) => s + t.targetQuantity, 0),
    0
  )

  if (loading) {
    return (
      <div className="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
        <div className="animate-pulse">
          <div className="h-8 bg-gray-200 rounded w-1/3 mb-4"></div>
          <div className="space-y-4">
            <div className="h-32 bg-gray-200 rounded"></div>
            <div className="h-32 bg-gray-200 rounded"></div>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
      <div className="px-4 py-6 sm:px-0">
        {/* Header */}
        <div className="flex justify-between items-start mb-6">
          <div>
            <Link href="/production" className="text-sm text-gray-500 hover:text-gray-700 mb-2 inline-block">
              ← Back to Production
            </Link>
            <h1 className="text-3xl font-bold text-gray-900">Stock Production</h1>
            <p className="mt-1 text-sm text-gray-500">
              {totalTasks} task{totalTasks !== 1 ? 's' : ''} | {totalQuantity} total units to produce
            </p>
          </div>
          <button
            onClick={() => setShowNewTaskModal(true)}
            className="bg-pink-600 text-white px-4 py-2 rounded-md hover:bg-pink-700 transition"
          >
            + New Stock Task
          </button>
        </div>

        {error && (
          <div className="bg-red-50 border border-red-200 rounded-lg p-4 mb-6">
            <p className="text-red-600">{error}</p>
          </div>
        )}

        {/* Low Stock Alert */}
        {inventory.length > 0 && (
          <div className="bg-amber-50 border border-amber-200 rounded-lg p-4 mb-6">
            <h3 className="font-medium text-amber-800 mb-2">Low Stock Items ({inventory.length})</h3>
            <div className="flex flex-wrap gap-2">
              {inventory.slice(0, 5).map(item => (
                <span
                  key={item.id}
                  className="inline-flex items-center px-3 py-1 rounded-full text-sm bg-amber-100 text-amber-800"
                >
                  {item.name}: {item.currentStock}/{item.minStock}
                </span>
              ))}
              {inventory.length > 5 && (
                <Link
                  href="/admin/inventory"
                  className="inline-flex items-center px-3 py-1 rounded-full text-sm bg-amber-200 text-amber-800 hover:bg-amber-300"
                >
                  +{inventory.length - 5} more →
                </Link>
              )}
            </div>
          </div>
        )}

        {/* Filter Tabs */}
        <div className="flex gap-2 mb-6">
          {(['pending', 'in_progress', 'all'] as const).map(f => (
            <button
              key={f}
              onClick={() => setFilter(f)}
              className={`px-4 py-2 rounded-md text-sm font-medium transition ${
                filter === f
                  ? 'bg-pink-600 text-white'
                  : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
              }`}
            >
              {f === 'pending' ? 'Pending' : f === 'in_progress' ? 'In Progress' : 'All'}
            </button>
          ))}
        </div>

        {/* Task List by Date */}
        {tasksByDate.length === 0 ? (
          <div className="bg-gray-50 border border-gray-200 rounded-lg p-8 text-center">
            <p className="text-gray-500">No stock production tasks found.</p>
            <button
              onClick={() => setShowNewTaskModal(true)}
              className="mt-4 text-pink-600 hover:text-pink-800"
            >
              Create a new task →
            </button>
          </div>
        ) : (
          <div className="space-y-6">
            {tasksByDate.map(dateGroup => (
              <div key={dateGroup.date} className="bg-white shadow rounded-lg overflow-hidden">
                {/* Date Header */}
                <div className="px-4 py-3 bg-gray-50 border-b border-gray-200">
                  <h3 className="text-lg font-semibold text-gray-900">
                    {formatDate(dateGroup.date)}
                  </h3>
                  <p className="text-sm text-gray-500">
                    {dateGroup.tasks.length} task{dateGroup.tasks.length !== 1 ? 's' : ''} |{' '}
                    {dateGroup.tasks.reduce((s, t) => s + t.targetQuantity, 0)} units
                  </p>
                </div>

                {/* Tasks */}
                <div className="divide-y divide-gray-100">
                  {dateGroup.tasks.map(task => (
                    <div
                      key={task.id}
                      className={`p-4 flex items-center justify-between hover:bg-gray-50 ${
                        task.priority > 0 ? 'border-l-4 border-red-400' : ''
                      }`}
                    >
                      <div className="flex-1">
                        <div className="flex items-center gap-2 mb-1">
                          <span className={`px-2 py-0.5 text-xs font-medium rounded ${
                            task.productType === 'CAKE_TIER' ? 'bg-orange-100 text-orange-800' :
                            task.productType === 'CUPCAKE' ? 'bg-pink-100 text-pink-800' :
                            task.productType === 'COOKIE' ? 'bg-amber-100 text-amber-800' :
                            'bg-gray-100 text-gray-800'
                          }`}>
                            {task.productType.replace('_', ' ')}
                          </span>
                          <span className={`px-2 py-0.5 text-xs font-medium rounded ${
                            task.status === 'PENDING' ? 'bg-gray-100 text-gray-700' :
                            task.status === 'IN_PROGRESS' ? 'bg-yellow-100 text-yellow-700' :
                            'bg-green-100 text-green-700'
                          }`}>
                            {task.status.replace('_', ' ')}
                          </span>
                          {task.isAutoGenerated && (
                            <span className="px-2 py-0.5 text-xs rounded bg-blue-100 text-blue-700">
                              Auto
                            </span>
                          )}
                        </div>
                        <h4 className="font-medium text-gray-900">{task.taskName}</h4>
                        <div className="flex items-center gap-3 text-sm text-gray-500 mt-1">
                          <span>{task.inventoryItemName}</span>
                          {task.flavor && <span>• {task.flavor}</span>}
                          <span>• {task.targetQuantity} units</span>
                          {task.durationMinutes && <span>• ~{task.durationMinutes}m</span>}
                        </div>
                        {task.assignedTo && (
                          <div className="text-sm text-gray-500 mt-1">
                            Assigned to: <span className="font-medium">{task.assignedTo}</span>
                          </div>
                        )}
                        {task.completedQuantity > 0 && task.completedQuantity < task.targetQuantity && (
                          <div className="mt-2">
                            <div className="w-32 bg-gray-200 rounded-full h-2">
                              <div
                                className="bg-green-500 h-2 rounded-full"
                                style={{ width: `${(task.completedQuantity / task.targetQuantity) * 100}%` }}
                              />
                            </div>
                            <span className="text-xs text-gray-500">
                              {task.completedQuantity}/{task.targetQuantity} done
                            </span>
                          </div>
                        )}
                      </div>

                      <div className="flex items-center gap-2">
                        {task.status === 'PENDING' && (
                          <button
                            onClick={() => handleStartTask(task.id)}
                            className="px-3 py-1 text-sm bg-yellow-100 text-yellow-700 rounded hover:bg-yellow-200"
                          >
                            Start
                          </button>
                        )}
                        {task.status === 'IN_PROGRESS' && (
                          <button
                            onClick={() => handleCompleteTask(task.id)}
                            className="px-3 py-1 text-sm bg-green-100 text-green-700 rounded hover:bg-green-200"
                          >
                            Complete
                          </button>
                        )}
                        {task.status === 'COMPLETED' && (
                          <span className="text-green-600 text-sm">Done</span>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Legend */}
        <div className="mt-6 bg-white shadow rounded-lg p-4">
          <h4 className="text-sm font-medium text-gray-700 mb-2">Product Types</h4>
          <div className="flex flex-wrap gap-3">
            <div className="flex items-center gap-1">
              <span className="px-2 py-0.5 text-xs font-medium rounded bg-orange-100 text-orange-800">CAKE TIER</span>
            </div>
            <div className="flex items-center gap-1">
              <span className="px-2 py-0.5 text-xs font-medium rounded bg-pink-100 text-pink-800">CUPCAKE</span>
            </div>
            <div className="flex items-center gap-1">
              <span className="px-2 py-0.5 text-xs font-medium rounded bg-amber-100 text-amber-800">COOKIE</span>
            </div>
            <div className="flex items-center gap-1">
              <span className="px-2 py-0.5 text-xs font-medium rounded bg-blue-100 text-blue-700">Auto</span>
              <span className="text-xs text-gray-500">= Auto-generated replenishment</span>
            </div>
          </div>
        </div>

        {/* New Task Modal */}
        {showNewTaskModal && (
          <NewStockTaskModal
            inventory={inventory}
            staff={staff}
            onClose={() => setShowNewTaskModal(false)}
            onCreated={() => {
              setShowNewTaskModal(false)
              loadData()
            }}
          />
        )}
      </div>
    </div>
  )
}

// Modal for creating new stock tasks
function NewStockTaskModal({
  inventory,
  staff,
  onClose,
  onCreated
}: {
  inventory: InventoryItem[]
  staff: Staff[]
  onClose: () => void
  onCreated: () => void
}) {
  const [allItems, setAllItems] = useState<InventoryItem[]>([])
  const [formData, setFormData] = useState({
    inventoryItemId: '',
    taskType: 'BAKE',
    targetQuantity: 10,
    scheduledDate: new Date().toISOString().split('T')[0],
    assignedToId: '',
    notes: ''
  })
  const [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    // Load all inventory items for selection
    fetch('/api/inventory')
      .then(res => res.json())
      .then(data => setAllItems(data))
      .catch(() => setAllItems(inventory))
  }, [inventory])

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!formData.inventoryItemId) {
      setError('Please select an inventory item')
      return
    }

    setSubmitting(true)
    setError(null)

    try {
      const selectedItem = allItems.find(i => i.id === parseInt(formData.inventoryItemId))
      const res = await fetch('/api/stock-tasks', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          inventoryItemId: parseInt(formData.inventoryItemId),
          taskType: formData.taskType,
          taskName: `${formData.taskType} ${formData.targetQuantity}x ${selectedItem?.name || 'item'}`,
          targetQuantity: formData.targetQuantity,
          scheduledDate: formData.scheduledDate,
          assignedToId: formData.assignedToId ? parseInt(formData.assignedToId) : null,
          notes: formData.notes || null
        })
      })

      if (!res.ok) throw new Error('Failed to create task')
      onCreated()
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to create task')
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-white rounded-lg shadow-lg p-6 w-full max-w-md">
        <h3 className="text-lg font-semibold text-gray-900 mb-4">New Stock Production Task</h3>

        {error && (
          <div className="bg-red-50 border border-red-200 rounded p-3 mb-4">
            <p className="text-red-600 text-sm">{error}</p>
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Inventory Item *</label>
            <select
              value={formData.inventoryItemId}
              onChange={e => setFormData(prev => ({ ...prev, inventoryItemId: e.target.value }))}
              className="w-full border border-gray-300 rounded-md px-3 py-2 text-sm"
              required
            >
              <option value="">Select an item...</option>
              {allItems.map(item => (
                <option key={item.id} value={item.id}>
                  {item.name} ({item.currentStock} in stock)
                </option>
              ))}
            </select>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Task Type</label>
              <select
                value={formData.taskType}
                onChange={e => setFormData(prev => ({ ...prev, taskType: e.target.value }))}
                className="w-full border border-gray-300 rounded-md px-3 py-2 text-sm"
              >
                <option value="BAKE">Bake</option>
                <option value="STACK">Stack</option>
                <option value="FROST">Frost</option>
                <option value="DECORATE">Decorate</option>
                <option value="PREP">Prep</option>
                <option value="PACKAGE">Package</option>
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Quantity</label>
              <input
                type="number"
                min="1"
                value={formData.targetQuantity}
                onChange={e => setFormData(prev => ({ ...prev, targetQuantity: parseInt(e.target.value) || 1 }))}
                className="w-full border border-gray-300 rounded-md px-3 py-2 text-sm"
              />
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Scheduled Date</label>
              <input
                type="date"
                value={formData.scheduledDate}
                onChange={e => setFormData(prev => ({ ...prev, scheduledDate: e.target.value }))}
                className="w-full border border-gray-300 rounded-md px-3 py-2 text-sm"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Assign To</label>
              <select
                value={formData.assignedToId}
                onChange={e => setFormData(prev => ({ ...prev, assignedToId: e.target.value }))}
                className="w-full border border-gray-300 rounded-md px-3 py-2 text-sm"
              >
                <option value="">Unassigned</option>
                {staff.map(s => (
                  <option key={s.id} value={s.id}>{s.name}</option>
                ))}
              </select>
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Notes</label>
            <textarea
              value={formData.notes}
              onChange={e => setFormData(prev => ({ ...prev, notes: e.target.value }))}
              className="w-full border border-gray-300 rounded-md px-3 py-2 text-sm"
              rows={2}
              placeholder="Optional notes..."
            />
          </div>

          <div className="flex justify-end gap-2 pt-4">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 text-sm text-gray-600 hover:text-gray-800"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={submitting}
              className="px-4 py-2 text-sm bg-pink-600 text-white rounded-md hover:bg-pink-700 disabled:opacity-50"
            >
              {submitting ? 'Creating...' : 'Create Task'}
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}
